package javatower.gui;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.*;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javatower.entities.Hero;
import javatower.entities.Item;
import javatower.systems.Shop;
import java.util.List;

/**
 * Buy/sell interface available between waves (opened with TAB).
 * <p>
 * The <b>BUY</b> section lists items generated by the {@link Shop} system,
 * scaled to the current wave. The <b>SELL</b> section lists all items
 * in the hero’s {@link javatower.systems.Inventory}.
 * Both sections are scrollable and refresh dynamically after each transaction.
 * </p>
 *
 * @author Vincent Chamberlain (2424309)
 * @see Shop
 * @see Hero#getInventory()
 */
public class ShopPanel extends VBox {
    private Hero hero;
    private Shop shop;
    private GameGUI gui;
    private VBox buySection, sellSection;
    private Label goldLabel, statusLabel;

    public ShopPanel(Hero hero, Shop shop, GameGUI gui) {
        this.hero = hero;
        this.shop = shop;
        this.gui = gui;
        setSpacing(12);
        setPadding(new Insets(20));
        setAlignment(Pos.TOP_CENTER);
        setStyle("-fx-background-color: #1a1a2e;");

        Label header = new Label("SHOP");
        header.setFont(Font.font("Monospaced", FontWeight.BOLD, 36));
        header.setStyle("-fx-text-fill: #e94560;");

        goldLabel = new Label();
        goldLabel.setFont(Font.font("Monospaced", FontWeight.BOLD, 22));
        goldLabel.setStyle("-fx-text-fill: #eab308;");

        statusLabel = new Label();
        statusLabel.setFont(Font.font("Monospaced", 16));
        statusLabel.setStyle("-fx-text-fill: #4ecca3;");

        Label buyHeader = new Label("-- BUY --");
        buyHeader.setFont(Font.font("Monospaced", FontWeight.BOLD, 20));
        buyHeader.setStyle("-fx-text-fill: #22d3ee;");

        buySection = new VBox(5);
        ScrollPane buyScroll = new ScrollPane(buySection);
        buyScroll.setFitToWidth(true);
        buyScroll.setPrefHeight(200);
        buyScroll.setStyle("-fx-background: #1a1a2e; -fx-background-color: #1a1a2e;");

        Label sellHeader = new Label("-- SELL (Inventory) --");
        sellHeader.setFont(Font.font("Monospaced", FontWeight.BOLD, 20));
        sellHeader.setStyle("-fx-text-fill: #f97316;");

        sellSection = new VBox(5);
        ScrollPane sellScroll = new ScrollPane(sellSection);
        sellScroll.setFitToWidth(true);
        sellScroll.setPrefHeight(200);
        sellScroll.setStyle("-fx-background: #1a1a2e; -fx-background-color: #1a1a2e;");

        Button backBtn = new Button("Back to Game");
        backBtn.setFont(Font.font("Monospaced", FontWeight.BOLD, 20));
        backBtn.setStyle("-fx-background-color: #e94560; -fx-text-fill: white; -fx-cursor: hand;");
        backBtn.setOnAction(e -> gui.returnToGame());

        getChildren().addAll(header, goldLabel, statusLabel, buyHeader, buyScroll, sellHeader, sellScroll, backBtn);
        refresh();
    }

    public void refresh() {
        goldLabel.setText("Gold: " + hero.getGold());
        statusLabel.setText("");

        // Buy items
        buySection.getChildren().clear();
        List<Item> stock = shop.getAvailableItems();
        for (Item item : stock) {
            HBox row = new HBox(10);
            row.setAlignment(Pos.CENTER_LEFT);

            String setTag = item.getEquipmentSet() != Item.EquipmentSet.NONE
                    ? " {" + item.getEquipmentSet().className + "}" : "";
            Label name = new Label(item.getName() + " [" + item.getRarity().name() + "]" + setTag);
            name.setFont(Font.font("Monospaced", 16));
            name.setStyle("-fx-text-fill: " + item.getRarity().color + ";");
            name.setPrefWidth(320);

            Label stats = new Label(item.getStatBonuses().toString());
            stats.setFont(Font.font("Monospaced", 14));
            stats.setStyle("-fx-text-fill: #aaa;");
            stats.setPrefWidth(200);

            Label price = new Label(item.getBuyPrice() + "g");
            price.setFont(Font.font("Monospaced", FontWeight.BOLD, 16));
            price.setStyle("-fx-text-fill: #eab308;");

            Button buyBtn = new Button("Buy");
            buyBtn.setStyle("-fx-background-color: #4ecca3; -fx-text-fill: white;");
            final Item itemRef = item;
            buyBtn.setOnAction(e -> {
                if (shop.buyItem(hero, itemRef)) {
                    statusLabel.setText("Bought " + itemRef.getName() + "!");
                } else {
                    statusLabel.setText("Not enough gold!");
                }
                refresh();
            });

            row.getChildren().addAll(name, stats, price, buyBtn);
            buySection.getChildren().add(row);
        }

        // Sell items
        sellSection.getChildren().clear();
        List<Item> inventory = hero.getInventory().getAllItems();
        for (Item item : inventory) {
            HBox row = new HBox(10);
            row.setAlignment(Pos.CENTER_LEFT);

            String setTag = item.getEquipmentSet() != Item.EquipmentSet.NONE
                    ? " {" + item.getEquipmentSet().className + "}" : "";
            Label name = new Label(item.getName() + " [" + item.getRarity().name() + "]" + setTag);
            name.setFont(Font.font("Monospaced", 16));
            name.setStyle("-fx-text-fill: " + item.getRarity().color + ";");
            name.setPrefWidth(320);

            Label price = new Label("+" + item.getSellPrice() + "g");
            price.setFont(Font.font("Monospaced", FontWeight.BOLD, 16));
            price.setStyle("-fx-text-fill: #eab308;");

            Button sellBtn = new Button("Sell");
            sellBtn.setStyle("-fx-background-color: #f97316; -fx-text-fill: white;");
            final Item itemRef = item;
            sellBtn.setOnAction(e -> {
                int gold = shop.sellItem(hero, itemRef);
                if (gold > 0) {
                    statusLabel.setText("Sold " + itemRef.getName() + " for " + gold + "g!");
                }
                refresh();
            });

            row.getChildren().addAll(name, price, sellBtn);
            sellSection.getChildren().add(row);
        }

        if (inventory.isEmpty()) {
            Label empty = new Label("No items to sell");
            empty.setStyle("-fx-text-fill: #666;");
            sellSection.getChildren().add(empty);
        }
    }
}
